version: 2
mergeable:
  - when: pull_request.*
    validate: []
    pass:
      - do: comment
        payload:
          body: >
            :warning:
            <h2>새로 만드는 AWS resource에 Team, Service 태그가 정의되었는지 반드시 확인 부탁드립니다.</h2>