version: 2
mergeable:
  - when: pull_request.*
    validate: []
    fail:
      - do: comment
        payload:
          body: >
            새로 만드는 AWS resource에 Team, Service 태그가 정의되었는지 반드시 확인 부탁드립니다.